import { IProduct } from "../entities/product-entity";

export const productos: IProduct[] = [
    { title: { es: "Nike Air", en: "Nike Air" }, description: { es: "Zapatillas deportivas Nike Air", en: "Nike Air sports shoes" }, price: { EUR: 120, DOLLAR: 150 }, sku: { "23131231": { color: "rojo", size: 40, image: "https://example.com/red_shoe.jpg", stock: 10 }, "41424141": { color: "azul", size: 42, image: "https://example.com/blue_shoe.jpg", stock: 5, }, }, stock: 15, featured: true ,image: "nikeAir.jpg", imageSmall: "nikeAirSmall.jpg"},
    { title: { es: "Nike Air", en: "Nike Air" }, description: { es: "Zapatillas deportivas Nike Air", en: "Nike Air sports shoes" }, price: { EUR: 120, DOLLAR: 150 }, sku: { "23131231": { color: "rojo", size: 40, image: "https://example.com/red_shoe.jpg", stock: 10 }, "41424141": { color: "azul", size: 42, image: "https://example.com/blue_shoe.jpg", stock: 5 } }, stock: 15, featured: true, image: "nikeAir.jpg", imageSmall: "nikeAirSmall.jpg" },
    { title: { es: "Adidas Ultraboost", en: "Adidas Ultraboost" }, description: { es: "Zapatillas deportivas Adidas Ultraboost", en: "Adidas Ultraboost sports shoes" }, price: { EUR: 140, DOLLAR: 170 }, sku: { "54545454": { color: "negro", size: 41, image: "https://example.com/black_shoe.jpg", stock: 8 }, "23232323": { color: "blanco", size: 43, image: "https://example.com/white_shoe.jpg", stock: 6 } }, stock: 14, featured: true, image: "adidasUltraboost.jpg", imageSmall: "adidasUltraboostSmall.jpg" },
    { title: { es: "Puma Running", en: "Puma Running" }, description: { es: "Zapatillas de correr Puma", en: "Puma running shoes" }, price: { EUR: 90, DOLLAR: 110 }, sku: { "67676767": { color: "verde", size: 42, image: "https://example.com/green_shoe.jpg", stock: 12 }, "78787878": { color: "gris", size: 44, image: "https://example.com/grey_shoe.jpg", stock: 4 } }, stock: 16, featured: true, image: "pumaRunning.jpg", imageSmall: "pumaRunningSmall.jpg" },
    { title: { es: "Reebok Classic", en: "Reebok Classic" }, description: { es: "Zapatillas clásicas Reebok", en: "Reebok classic shoes" }, price: { EUR: 75, DOLLAR: 95 }, sku: { "12121212": { color: "negro", size: 40, image: "https://example.com/black_reebok.jpg", stock: 7 }, "34343434": { color: "blanco", size: 41, image: "https://example.com/white_reebok.jpg", stock: 10 } }, stock: 17, featured: true, image: "reebokClassic.jpg", imageSmall: "reebokClassicSmall.jpg" },
    { title: { es: "Converse All Star", en: "Converse All Star" }, description: { es: "Zapatillas Converse All Star", en: "Converse All Star shoes" }, price: { EUR: 65, DOLLAR: 80 }, sku: { "56565656": { color: "rojo", size: 39, image: "https://example.com/red_converse.jpg", stock: 9 }, "78787878": { color: "azul", size: 40, image: "https://example.com/blue_converse.jpg", stock: 6 } }, stock: 15, featured: true, image: "converseAllStar.jpg", imageSmall: "converseAllStarSmall.jpg" },
    { title: { es: "Vans Old Skool", en: "Vans Old Skool" }, description: { es: "Zapatillas Vans Old Skool", en: "Vans Old Skool shoes" }, price: { EUR: 70, DOLLAR: 85 }, sku: { "23232323": { color: "negro", size: 42, image: "https://example.com/black_vans.jpg", stock: 11 }, "65656565": { color: "blanco", size: 41, image: "https://example.com/white_vans.jpg", stock: 5 } }, stock: 16, featured: true, image: "vansOldSkool.jpg", imageSmall: "vansOldSkoolSmall.jpg" },
    { title: { es: "New Balance 574", en: "New Balance 574" }, description: { es: "Zapatillas New Balance 574", en: "New Balance 574 shoes" }, price: { EUR: 80, DOLLAR: 100 }, sku: { "89898989": { color: "gris", size: 43, image: "https://example.com/grey_nb.jpg", stock: 10 }, "98989898": { color: "azul", size: 44, image: "https://example.com/blue_nb.jpg", stock: 8 } }, stock: 18, featured: true, image: "newBalance574.jpg", imageSmall: "newBalance574Small.jpg" },
    { title: { es: "Asics Gel-Kayano", en: "Asics Gel-Kayano" }, description: { es: "Zapatillas Asics Gel-Kayano", en: "Asics Gel-Kayano shoes" }, price: { EUR: 130, DOLLAR: 160 }, sku: { "32323232": { color: "negro", size: 41, image: "https://example.com/black_asics.jpg", stock: 9 }, "12121212": { color: "blanco", size: 42, image: "https://example.com/white_asics.jpg", stock: 7 } }, stock: 16, featured: true, image: "asicsGelKayano.jpg", imageSmall: "asicsGelKayanoSmall.jpg" },
    { title: { es: "Fila Disruptor", en: "Fila Disruptor" }, description: { es: "Zapatillas Fila Disruptor", en: "Fila Disruptor shoes" }, price: { EUR: 85, DOLLAR: 105 }, sku: { "89898989": { color: "blanco", size: 39, image: "https://example.com/white_fila.jpg", stock: 12 }, "12121212": { color: "negro", size: 40, image: "https://example.com/black_fila.jpg", stock: 8 } }, stock: 20, featured: true, image: "filaDisruptor.jpg", imageSmall: "filaDisruptorSmall.jpg" },
    { title: { es: "Under Armour HOVR", en: "Under Armour HOVR" }, description: { es: "Zapatillas Under Armour HOVR", en: "Under Armour HOVR shoes" }, price: { EUR: 110, DOLLAR: 135 }, sku: { "54545454": { color: "azul", size: 42, image: "https://example.com/blue_ua.jpg", stock: 10 }, "67676767": { color: "gris", size: 43, image: "https://example.com/grey_ua.jpg", stock: 7 } }, stock: 17, featured: true, image: "underArmourHovr.jpg", imageSmall: "underArmourHovrSmall.jpg" },
    { title: { es: "Salomon Speedcross", en: "Salomon Speedcross" }, description: { es: "Zapatillas de trail Salomon Speedcross", en: "Salomon Speedcross trail shoes" }, price: { EUR: 120, DOLLAR: 150 }, sku: { "98989898": { color: "negro", size: 41, image: "https://example.com/black_salomon.jpg", stock: 6 }, "12121212": { color: "azul", size: 42, image: "https://example.com/blue_salomon.jpg", stock: 8 } }, stock: 14, featured: true, image: "salomonSpeedcross.jpg", imageSmall: "salomonSpeedcrossSmall.jpg" },
    { title: { es: "Brooks Ghost", en: "Brooks Ghost" }, description: { es: "Zapatillas Brooks Ghost", en: "Brooks Ghost shoes" }, price: { EUR: 110, DOLLAR: 135 }, sku: { "56565656": { color: "negro", size: 40, image: "https://example.com/black_brooks.jpg", stock: 11 }, "78787878": { color: "blanco", size: 41, image: "https://example.com/white_brooks.jpg", stock: 9 } }, stock: 20, featured: true, image: "brooksGhost.jpg", imageSmall: "brooksGhostSmall.jpg" },
    { title: { es: "Mizuno Wave Rider", en: "Mizuno Wave Rider" }, description: { es: "Zapatillas Mizuno Wave Rider", en: "Mizuno Wave Rider shoes" }, price: { EUR: 100, DOLLAR: 125 }, sku: { "98989898": { color: "azul", size: 42, image: "https://example.com/blue_mizuno.jpg", stock: 10 }, "67676767": { color: "gris", size: 43, image: "https://example.com/grey_mizuno.jpg", stock: 7 } }, stock: 17, featured: true, image: "mizunoWaveRider.jpg", imageSmall: "mizunoWaveRiderSmall.jpg" },
    { title: { es: "Saucony Triumph", en: "Saucony Triumph" }, description: { es: "Zapatillas Saucony Triumph", en: "Saucony Triumph shoes" }, price: { EUR: 115, DOLLAR: 145 }, sku: { "23232323": { color: "negro", size: 41, image: "https://example.com/black_saucony.jpg", stock: 9 }, "34343434": { color: "azul", size: 42, image: "https://example.com/blue_saucony.jpg", stock: 6 } }, stock: 15, featured: true, image: "sauconyTriumph.jpg", imageSmall: "sauconyTriumphSmall.jpg" },
    { title: { es: "Hoka One One", en: "Hoka One One" }, description: { es: "Zapatillas Hoka One One", en: "Hoka One One shoes" }, price: { EUR: 130, DOLLAR: 160 }, sku: { "78787878": { color: "negro", size: 40, image: "https://example.com/black_hoka.jpg", stock: 8 }, "98989898": { color: "blanco", size: 41, image: "https://example.com/white_hoka.jpg", stock: 7 } }, stock: 15, featured: true, image: "hokaOneOne.jpg", imageSmall: "hokaOneOneSmall.jpg" },
    { title: { es: "Merrell Moab", en: "Merrell Moab" }, description: { es: "Botas de senderismo Merrell Moab", en: "Merrell Moab hiking boots" }, price: { EUR: 100, DOLLAR: 125 }, sku: { "12121212": { color: "marrón", size: 42, image: "https://example.com/brown_merrell.jpg", stock: 7 }, "89898989": { color: "verde", size: 43, image: "https://example.com/green_merrell.jpg", stock: 10 } }, stock: 17, featured: true, image: "merrellMoab.jpg", imageSmall: "merrellMoabSmall.jpg" },
    { title: { es: "Timberland Chukka", en: "Timberland Chukka" }, description: { es: "Botas Timberland Chukka", en: "Timberland Chukka boots" }, price: { EUR: 150, DOLLAR: 180 }, sku: { "67676767": { color: "marrón", size: 41, image: "https://example.com/brown_timberland.jpg", stock: 5 }, "78787878": { color: "negro", size: 42, image: "https://example.com/black_timberland.jpg", stock: 6 } }, stock: 11, featured: true, image: "timberlandChukka.jpg", imageSmall: "timberlandChukkaSmall.jpg" },
    { title: { es: "Columbia Redmond", en: "Columbia Redmond" }, description: { es: "Botas de senderismo Columbia Redmond", en: "Columbia Redmond hiking boots" }, price: { EUR: 110, DOLLAR: 135 }, sku: { "54545454": { color: "marrón", size: 43, image: "https://example.com/brown_columbia.jpg", stock: 8 }, "23232323": { color: "gris", size: 44, image: "https://example.com/grey_columbia.jpg", stock: 6 } }, stock: 14, featured: true, image: "columbiaRedmond.jpg", imageSmall: "columbiaRedmondSmall.jpg" },
    { title: { es: "The North Face Ultra", en: "The North Face Ultra" }, description: { es: "Zapatillas de trail The North Face Ultra", en: "The North Face Ultra trail shoes" }, price: { EUR: 125, DOLLAR: 155 }, sku: { "12121212": { color: "negro", size: 42, image: "https://example.com/black_northface.jpg", stock: 7 }, "34343434": { color: "azul", size: 43, image: "https://example.com/blue_northface.jpg", stock: 8 } }, stock: 15, featured: true, image: "northFaceUltra.jpg", imageSmall: "northFaceUltraSmall.jpg" },
    { title: { es: "Lowa Renegade", en: "Lowa Renegade" }, description: { es: "Botas de senderismo Lowa Renegade", en: "Lowa Renegade hiking boots" }, price: { EUR: 160, DOLLAR: 200 }, sku: { "23232323": { color: "marrón", size: 42, image: "https://example.com/brown_lowa.jpg", stock: 6 }, "67676767": { color: "gris", size: 43, image: "https://example.com/grey_lowa.jpg", stock: 7 } }, stock: 13, featured: true, image: "lowaRenegade.jpg", imageSmall: "lowaRenegadeSmall.jpg" },
    { title: { es: "Arc'teryx Norvan", en: "Arc'teryx Norvan" }, description: { es: "Zapatillas de trail Arc'teryx Norvan", en: "Arc'teryx Norvan trail shoes" }, price: { EUR: 140, DOLLAR: 175 }, sku: { "78787878": { color: "negro", size: 41, image: "https://example.com/black_arcteryx.jpg", stock: 9 }, "98989898": { color: "azul", size: 42, image: "https://example.com/blue_arcteryx.jpg", stock: 5 } }, stock: 14, featured: true, image: "arcteryxNorvan.jpg", imageSmall: "arcteryxNorvanSmall.jpg" },
    { title: { es: "Keen Targhee", en: "Keen Targhee" }, description: { es: "Botas de senderismo Keen Targhee", en: "Keen Targhee hiking boots" }, price: { EUR: 100, DOLLAR: 125 }, sku: { "12121212": { color: "marrón", size: 42, image: "https://example.com/brown_keen.jpg", stock: 10 }, "89898989": { color: "verde", size: 43, image: "https://example.com/green_keen.jpg", stock: 7 } }, stock: 17, featured: true, image: "keenTarghee.jpg", imageSmall: "keenTargheeSmall.jpg" }
];
